options:
  max-time: 20
pipelines:
  default:
    - step: &test
        name: Test
        image: openjdk:11-jdk-buster
        caches:
          - gradle
        script:
          - ./gradlew test
  branches:
    main:
      - step: *test
      - step:
          name: Release
          image: node:18
          script:
            - git describe --exact-match && exit
            - npx standard-version
            - git push --follow-tags
  tags:
    "*":
      - step:
          name: Publish
          deployment: Production
          image: openjdk:11-jdk-buster
          caches:
            - gradle
          script:
            - ./bin/init-gpg.sh
            - ./gradlew properties | grep version
            - ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
